server:
  port: 8083
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/my_database}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:admin}
    password: password123
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  service:
    profile: "http://localhost:8081/profile"