server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  profiles:
    active: test
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password123
